#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_3cx_sbc_connections(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/3cx_sbc_connections", plugins_dir + "/3cx_sbc_connections")

bakery_info["3cx_sbc_connections"] = {
    "bake_function" : bake_3cx_sbc_connections,
    "os"            : [ "linux", ],
}