#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_baruwa_mailq(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/baruwa_mailq", plugins_dir + "/baruwa_mailq")

bakery_info["baruwa_mailq"] = {
    "bake_function" : bake_baruwa_mailq,
    "os"            : [ "linux", ],
}