#!/usr/bin/python
def inventory_3cx_sbc_connections(info):
    yield "Count", None

def check_3cx_sbc_connections(item, params, info):
    perfdata = []
    count = 0
    crit = 1
    for line in info:
        count = count + 1
    perfdata = [("SBC Count", count)]
    if count < crit:
        status = 2
    else:
        status = 0
    return status, "SBC Count is "+str(count), perfdata

#factory_settings["3cx_sbc_connections_default_params"] = {
#        "count"     : (0, 0),
#}


check_info['3cx_sbc_connections'] = {
    "check_function":             check_3cx_sbc_connections,
    "inventory_function":        inventory_3cx_sbc_connections,
    "service_description":       "3CX SBC Connection",
    "has_perfdata":              True,
    "group":                     "3cx_sbc_connections",
    "default_levels_variable" :  "3cx_sbc_connections_default_params",
}
